package main

import (
	"go/ast"
	"go/parser"
	"go/token"
	"testing"
)

func TestParseNolint(t *testing.T) {
	for _, tc := range []struct {
		text  string
		ok    bool
		all   bool
		names []string
	}{
		{"//nolint", true, true, nil},
		{"// nolint", true, true, nil},
		{"//nolint // flaky upstream", true, true, nil},
		{"//nolint:all", true, true, nil},
		{"//nolint:errcheck,SA1019", true, false, []string{"errcheck", "sa1019"}},
		{"//nolint:govet // reason", true, false, []string{"govet"}},
		{"//nolintfoo", false, false, nil},
		{"// not a directive", false, false, nil},
	} {
		names, ok := parseNolint(tc.text)
		if ok != tc.ok {
			t.Errorf("%q: ok=%v, want %v", tc.text, ok, tc.ok)
			continue
		}
		if !ok {
			continue
		}
		if (names == nil) != tc.all {
			t.Errorf("%q: all=%v, want %v", tc.text, names == nil, tc.all)
			continue
		}
		for _, n := range tc.names {
			if !names[n] {
				t.Errorf("%q: missing name %q in %v", tc.text, n, names)
			}
		}
	}
}

func TestLinterNames(t *testing.T) {
	for analyzer, want := range map[string]string{
		"SA1019":     "staticcheck",
		"S1000":      "gosimple",
		"ST1005":     "stylecheck",
		"printf":     "govet",
		"stdmethods": "govet", // a vet pass, not a staticcheck code
	} {
		got := linterNames(analyzer)
		found := false
		for _, n := range got {
			found = found || n == want
		}
		if !found {
			t.Errorf("linterNames(%q) = %v, want it to include %q", analyzer, got, want)
		}
	}
}

const suppressSrc = `package p

import "fmt"

func inline() {
	fmt.Printf("%d", "x") //nolint:printf
}

//nolint:govet
func block() {
	fmt.Printf("%d", "x")
}

func other() {
	fmt.Printf("%d", "x") //nolint:errcheck
}
`

func TestSuppresses(t *testing.T) {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, "p.go", suppressSrc, parser.ParseComments)
	if err != nil {
		t.Fatal(err)
	}
	idx := indexNolint(fset, []*ast.File{f})
	lineStart := func(line int) token.Pos { return fset.File(f.Pos()).LineStart(line) }
	for line, want := range map[int]bool{
		6:  true,  // inline //nolint:printf on the same line
		11: true,  // inside the func a standalone //nolint:govet precedes
		15: false, // //nolint:errcheck names another linter
	} {
		if got := idx.suppresses("printf", lineStart(line)); got != want {
			t.Errorf("line %d: suppresses=%v, want %v", line, got, want)
		}
	}
}

func TestGeneratedFilesSuppressed(t *testing.T) {
	fset := token.NewFileSet()
	src := "// Code generated by x. DO NOT EDIT.\n\npackage p\n\nvar _ = 1\n"
	f, err := parser.ParseFile(fset, "gen.go", src, parser.ParseComments)
	if err != nil {
		t.Fatal(err)
	}
	if !indexNolint(fset, []*ast.File{f}).suppresses("printf", f.Decls[0].Pos()) {
		t.Error("diagnostic in a generated file was not suppressed")
	}
}
