_: {
  projectRootFile = "flake.nix";
  programs.nixfmt.enable = true;
  linters = {
    statix.enable = true;
    deadnix.enable = true;
    # igloo has neither go.mod nor Cargo.toml at the tree root, so
    # eng-versioning(7) can't derive the key; pin it explicitly (eng-versioning.nix).
    eng-versioning.key = "IGLOO_VERSION";
  };
  settings.excludes = [
    # generated by bun2nix — not hand-authored nix
    "pkgs/build-support/bun2nix/lint/bun.nix"
    # exploratory proofs-of-concept; not held to lint standards
    "zz-pocs/**"
  ];
}
