{ ... }:
{
  projectRootFile = "flake.nix";
  programs.nixfmt.enable = true;
  # Disabled: conformist's linter CHECK path (format/check.go -> linter.go)
  # does not chunk matched files for a `no-positional-arg-support` linter the
  # way the formatter Apply/repair path does (scheduler.go / sandbox.go). With
  # 81 nix files matching `*.nix`, `statix check` fails outright with
  # "formatter cannot format multiple files at once". Re-enable once fixed
  # upstream; flagged to eng for filing.
  linters.statix.enable = false;
  linters.deadnix.enable = true;
  # igloo has neither go.mod nor Cargo.toml at the tree root, so
  # eng-versioning(7) can't derive the key; pin it explicitly (eng-versioning.nix).
  linters.eng-versioning.key = "IGLOO_VERSION";
  settings.excludes = [
    # generated by bun2nix — not hand-authored nix
    "pkgs/build-support/bun2nix/lint/bun.nix"
    # exploratory proofs-of-concept; not held to lint standards
    "zz-pocs/**"
  ];
}
