# codegen repair (igloo#80): codegenCheck's passthru.codegenPatch is the
# generators' diff against src (apply with `git apply -p2`), and codegenCheck is
# "that patch is empty". Fixtures build on the manifest fixture: a stale tree
# for a chained command — go generate rewrites generated.go, a second step
# renders a non-Go schema into a new schema_gen.go, a third deletes an output the
# chain no longer produces — and the tree that patch repairs it to.
{
  pkgs,
  system,
  # a buildGoAuto module over the (current) manifest fixture
  manifestAuto,
}:
let
  fixture = ./manifest;
  codegenIncludes = [ "*.schema" ];
  chainedCheck =
    pname: src:
    (pkgs.buildGodynModule {
      inherit pname src;
      manifest = ./manifest/go.nix;
      inputs.dep.packages.${system}.go-pkgs = ./cross;
      version = "0.0.0";
      subPackages = [ "." ];
    }).passthru.codegenCheck
      {
        command = ''
          go generate ./...
          printf 'package main\n\nconst schemaGreeting = "%s"\n' "$(cat greeting.schema)" > schema_gen.go
          rm -f obsolete_gen.go
        '';
        inherit codegenIncludes;
      };

  staleSrc = pkgs.runCommandLocal "godyn-codegen-stale-src" { } ''
    cp -r --no-preserve=mode ${fixture} $out
    # generated.go from an older generator
    printf '// Code generated by tools/gen. DO NOT EDIT.\n\npackage main\n\nconst generated = "stale"\n' > $out/generated.go
    # the schema's rendering, schema_gen.go, was never committed
    printf 'hello schema\n' > $out/greeting.schema
    printf '// Code generated by an earlier chain. DO NOT EDIT.\n\npackage main\n' > $out/obsolete_gen.go
  '';
  staleCheck = chainedCheck "godyn-codegen-stale" staleSrc;

  repairedSrc =
    pkgs.runCommandLocal "godyn-codegen-repaired-src" { nativeBuildInputs = [ pkgs.git ]; }
      ''
        cp -r --no-preserve=mode ${staleSrc} $out
        cd $out
        git apply -p2 ${staleCheck.passthru.codegenPatch}/patch
      '';
  repairedCheck = chainedCheck "godyn-codegen-repaired" repairedSrc;

  # the current fixture through buildGoAuto (the existing green codegen check)
  currentCheck = manifestAuto.passthru.codegenCheck { command = "go generate ./..."; };
  # a generator writing the toolchain's store path: the repair still carries it
  # (the check base's disallowedReferences = [ go ] must not reach the patch)
  goRefPatch =
    (manifestAuto.passthru.codegenCheck { command = "go env GOROOT > goroot.txt"; })
    .passthru.codegenPatch;
in
{
  # stale: the patch is non-empty and repairs the tree (modify, create, delete);
  # repaired, the same check passes and its patch is empty. current: empty patch,
  # passing check. codegenIncludes surfaces as passthru (default [ ]).
  godyn-codegen-patch-test =
    assert staleCheck.passthru.codegenIncludes == codegenIncludes;
    assert currentCheck.passthru.codegenIncludes == [ ];
    pkgs.runCommandLocal "godyn-codegen-patch-test-check" { } ''
      [ -s ${staleCheck.passthru.codegenPatch}/patch ] || { echo "stale tree: empty codegenPatch" >&2; exit 1; }
      diff -u ${fixture}/generated.go ${repairedSrc}/generated.go
      grep -qx 'const schemaGreeting = "hello schema"' ${repairedSrc}/schema_gen.go \
        || { echo "repaired tree: schema_gen.go not rendered" >&2; exit 1; }
      [ ! -e ${repairedSrc}/obsolete_gen.go ] || { echo "repaired tree: obsolete_gen.go not deleted" >&2; exit 1; }
      [ ! -s ${repairedCheck.passthru.codegenPatch}/patch ] || {
        echo "repaired tree: codegenPatch not empty" >&2; cat ${repairedCheck.passthru.codegenPatch}/patch >&2; exit 1; }
      [ ! -s ${currentCheck.passthru.codegenPatch}/patch ] || {
        echo "current tree: codegenPatch not empty" >&2; cat ${currentCheck.passthru.codegenPatch}/patch >&2; exit 1; }
      grep -q '^+++ b/work/goroot.txt$' ${goRefPatch}/patch || { echo "go-referencing output: not in the patch" >&2; exit 1; }
      # both checks pass (building them is the assertion)
      echo ${repairedCheck} ${currentCheck} > $out
    '';
  # the stale tree's check fails naming the drift and where its repair lives
  godyn-codegen-patch-drift-test = pkgs.testers.testBuildFailure' {
    drv = staleCheck;
    expectedBuilderLogEntries = [
      "godyn codegen drift (godyn-codegen-stale)"
      "git apply -p2 "
    ];
  };
}
