# codegen repair (igloo#80): codegenCheck's passthru.codegenPatch is the
# generators' diff against src (apply with `git apply -p2`), and codegenCheck is
# "that patch is empty". Fixtures build on the manifest fixture: a stale tree
# for a chained command — go generate rewrites generated.go, a second step
# renders a non-Go schema into a new schema_gen.go, a third deletes an output the
# chain no longer produces — and the tree that patch repairs it to.
{
  pkgs,
  system,
  # the flake's own self, for igloo#83's codegenPrefix fixtures (self + "/subdir"
  # is the only src shape codegenPrefixOf can derive a real subdirectory from —
  # see build-godyn-module.nix's codegenPrefixOf).
  self,
  # a buildGoAuto module over the (current) manifest fixture
  manifestAuto,
}:
let
  fixture = ./manifest;
  codegenIncludes = [ "*.schema" ];
  chainedCheck =
    pname: src:
    (pkgs.buildGodynModule {
      inherit pname src;
      manifest = ./manifest/go.nix;
      inputs.dep.packages.${system}.go-pkgs = ./cross;
      version = "0.0.0";
      subPackages = [ "." ];
    }).passthru.codegenCheck
      {
        command = ''
          go generate ./...
          printf 'package main\n\nconst schemaGreeting = "%s"\n' "$(cat greeting.schema)" > schema_gen.go
          rm -f obsolete_gen.go
        '';
        inherit codegenIncludes;
      };

  staleSrc = pkgs.runCommandLocal "godyn-codegen-stale-src" { } ''
    cp -r --no-preserve=mode ${fixture} $out
    # generated.go from an older generator
    printf '// Code generated by tools/gen. DO NOT EDIT.\n\npackage main\n\nconst generated = "stale"\n' > $out/generated.go
    # the schema's rendering, schema_gen.go, was never committed
    printf 'hello schema\n' > $out/greeting.schema
    printf '// Code generated by an earlier chain. DO NOT EDIT.\n\npackage main\n' > $out/obsolete_gen.go
  '';
  staleCheck = chainedCheck "godyn-codegen-stale" staleSrc;

  repairedSrc =
    pkgs.runCommandLocal "godyn-codegen-repaired-src" { nativeBuildInputs = [ pkgs.git ]; }
      ''
        cp -r --no-preserve=mode ${staleSrc} $out
        cd $out
        git apply -p2 ${staleCheck.passthru.codegenPatch}/patch
      '';
  repairedCheck = chainedCheck "godyn-codegen-repaired" repairedSrc;

  # the current fixture through buildGoAuto (the existing green codegen check)
  currentCheck = manifestAuto.passthru.codegenCheck { command = "go generate ./..."; };
  # a generator writing the toolchain's store path: the repair still carries it
  # (the check base's disallowedReferences = [ go ] must not reach the patch)
  goRefPatch =
    (manifestAuto.passthru.codegenCheck { command = "go env GOROOT > goroot.txt"; })
    .passthru.codegenPatch;

  # igloo#83: codegenPrefix. Reuses the all-local `ldflags` fixture (a real
  # go.mod, no third-party deps) purely as a module tree; codegenCheck's
  # checkBase unconditionally needs `modules`, so a schema-only gomod2nix.toml
  # (the same shape an all-local module's own toml has — see e.g.
  # tests/testldflags/gomod2nix.toml) satisfies it without a real vendor tree.
  # One buildGodynModule instance per distinct `src` shape, each producing
  # multiple codegenCheck calls off it (as currentCheck/goRefPatch already do
  # off manifestAuto above), rather than one instance per check.
  ldflagsFixture = ./ldflags;
  emptyModules = builtins.toFile "gomod2nix.toml" "schema = 3\n";
  prefixRelPath = "pkgs/build-support/godyn/tests/ldflags";
  # self + "/<subdir>" — the documented convention (mkGoPkgs(7)) for a module
  # rooted below the flake root — auto-derives the real repo-relative prefix.
  subdirModule = pkgs.buildGodynModule {
    pname = "godyn-codegen-prefix-subdir";
    src = self + "/${prefixRelPath}";
    modules = emptyModules;
  };
  subdirCheck = subdirModule.passthru.codegenCheck {
    command = "echo codegen-prefix-marker > CODEGEN_PREFIX_MARKER.txt";
  };
  # explicit always wins, even over a src that would auto-derive a real prefix.
  explicitOverrideCheck = subdirModule.passthru.codegenCheck {
    command = "true";
    codegenPrefix = "elsewhere";
  };
  # a bare path literal (like every pre-existing fixture in this file): its own
  # independent store copy, indistinguishable from "src IS the flake root" by
  # context alone -> null, never a guessed "".
  bareModule = pkgs.buildGodynModule {
    pname = "godyn-codegen-prefix-bare";
    src = ldflagsFixture;
    modules = emptyModules;
  };
  bareCheck = bareModule.passthru.codegenCheck { command = "true"; };
  # the escape hatch for a root module: bare src can't auto-derive "" (see
  # codegenPrefixOf), so a caller who knows their module IS the repo root
  # passes it explicitly.
  explicitRootCheck = bareModule.passthru.codegenCheck {
    command = "true";
    codegenPrefix = "";
  };
in
{
  # stale: the patch is non-empty and repairs the tree (modify, create, delete);
  # repaired, the same check passes and its patch is empty. current: empty patch,
  # passing check. codegenIncludes surfaces as passthru (default [ ]).
  godyn-codegen-patch-test =
    assert staleCheck.passthru.codegenIncludes == codegenIncludes;
    assert currentCheck.passthru.codegenIncludes == [ ];
    pkgs.runCommandLocal "godyn-codegen-patch-test-check" { } ''
      [ -s ${staleCheck.passthru.codegenPatch}/patch ] || { echo "stale tree: empty codegenPatch" >&2; exit 1; }
      diff -u ${fixture}/generated.go ${repairedSrc}/generated.go
      grep -qx 'const schemaGreeting = "hello schema"' ${repairedSrc}/schema_gen.go \
        || { echo "repaired tree: schema_gen.go not rendered" >&2; exit 1; }
      [ ! -e ${repairedSrc}/obsolete_gen.go ] || { echo "repaired tree: obsolete_gen.go not deleted" >&2; exit 1; }
      [ ! -s ${repairedCheck.passthru.codegenPatch}/patch ] || {
        echo "repaired tree: codegenPatch not empty" >&2; cat ${repairedCheck.passthru.codegenPatch}/patch >&2; exit 1; }
      [ ! -s ${currentCheck.passthru.codegenPatch}/patch ] || {
        echo "current tree: codegenPatch not empty" >&2; cat ${currentCheck.passthru.codegenPatch}/patch >&2; exit 1; }
      grep -q '^+++ b/work/goroot.txt$' ${goRefPatch}/patch || { echo "go-referencing output: not in the patch" >&2; exit 1; }
      # both checks pass (building them is the assertion)
      echo ${repairedCheck} ${currentCheck} > $out
    '';
  # the stale tree's check fails naming the drift and where its repair lives
  godyn-codegen-patch-drift-test = pkgs.testers.testBuildFailure' {
    drv = staleCheck;
    expectedBuilderLogEntries = [
      "godyn codegen drift (godyn-codegen-stale)"
      "git apply -p2 "
    ];
  };
  # igloo#83: codegenPrefix. `self + "/subdir"` auto-derives the real
  # repo-relative path; a bare path literal (like every pre-existing fixture
  # above, none of which carry a codegenPrefix) stays null; explicit always
  # wins, including "" for a root module (the auto-derivation escape hatch).
  # The build check applies subdirCheck's patch from a SIMULATED repo root
  # with conformist#124's own convention — `git apply -p2 --directory=<the
  # auto-derived prefix>` — and asserts the marker lands at the module's real
  # nested path, never at the simulated repo root.
  godyn-codegen-prefix-test =
    assert subdirCheck.passthru.codegenPrefix == prefixRelPath;
    assert bareCheck.passthru.codegenPrefix == null;
    assert explicitOverrideCheck.passthru.codegenPrefix == "elsewhere";
    assert explicitRootCheck.passthru.codegenPrefix == "";
    assert staleCheck.passthru.codegenPrefix == null;
    assert currentCheck.passthru.codegenPrefix == null;
    pkgs.runCommandLocal "godyn-codegen-prefix-test-check" { nativeBuildInputs = [ pkgs.git ]; } ''
      mkdir -p "$TMPDIR/repo/$(dirname ${prefixRelPath})"
      cp -r --no-preserve=mode ${ldflagsFixture} "$TMPDIR/repo/${prefixRelPath}"
      cd "$TMPDIR/repo"
      git apply -p2 --directory=${prefixRelPath} ${subdirCheck.passthru.codegenPatch}/patch
      [ -f ${prefixRelPath}/CODEGEN_PREFIX_MARKER.txt ] || {
        echo "codegenPrefix repair: marker not created at ${prefixRelPath}/ under the simulated repo root" >&2; exit 1; }
      [ ! -f CODEGEN_PREFIX_MARKER.txt ] || {
        echo "codegenPrefix repair: marker wrongly created at the simulated repo root instead of ${prefixRelPath}/" >&2; exit 1; }
      grep -qx 'codegen-prefix-marker' ${prefixRelPath}/CODEGEN_PREFIX_MARKER.txt || {
        echo "codegenPrefix repair: marker content mismatch" >&2; exit 1; }
      echo OK > $out
    '';
}
