schema = 3

[mod]

  [mod.'filippo.io/age']
    version = 'v1.3.1'
    hash = 'sha256-Qs/q3zQYV0PukABBPf/aU5V1oOhw95NG6K301VYJk8A='
    goVersion = '1.24.0'
    vendorPackages = [
      'filippo.io/age',
      'filippo.io/age/internal/bech32',
      'filippo.io/age/internal/format',
      'filippo.io/age/internal/stream'
    ]


  [mod.'filippo.io/hpke']
    version = 'v0.4.0'
    hash = 'sha256-xKPT2hMzz/i3xdDK3NKn6FOmfQPxIMgxCOmm8U1heY4='
    goVersion = '1.24.0'
    vendorPackages = [
      'filippo.io/hpke',
      'filippo.io/hpke/crypto',
      'filippo.io/hpke/crypto/ecdh',
      'filippo.io/hpke/internal/byteorder'
    ]



  [mod.'github.com/DataDog/zstd']
    version = 'v1.5.7'
    hash = 'sha256-GlSZOyix7Ct7tOKmSKpGckDjMhTtiYPBTpoWdwGLx5M='
    goVersion = '1.14'
    vendorPackages = [
      'github.com/DataDog/zstd'
    ]


  [mod.'github.com/amarbel-llc/tommy']
    version = 'v0.0.0-20260405143331-87255e87bf37'
    hash = 'sha256-ElzACYuPmWpNk7bm4V8de18P+PqG+92X9aSxJg8gRUI='
    goVersion = '1.26'
    vendorPackages = [
      'github.com/amarbel-llc/tommy/internal/lexer',
      'github.com/amarbel-llc/tommy/internal/ringbuf',
      'github.com/amarbel-llc/tommy/pkg/cst',
      'github.com/amarbel-llc/tommy/pkg/document'
    ]





  [mod.'github.com/brandondube/tai']
    version = 'v0.1.0'
    hash = 'sha256-o32wvMW6waT/vJJkpjiCGxBNBUsqeAvnARhbsikRk50='
    goVersion = '1.16'
    vendorPackages = [
      'github.com/brandondube/tai'
    ]




























































  [mod.'golang.org/x/crypto']
    version = 'v0.50.0'
    hash = 'sha256-vC1BJT7+3UBWLyEE5n3to0NKhMo6m2HGow2HiFgpQLo='
    goVersion = '1.25.0'
    vendorPackages = [
      'golang.org/x/crypto/blowfish',
      'golang.org/x/crypto/chacha20',
      'golang.org/x/crypto/chacha20poly1305',
      'golang.org/x/crypto/curve25519',
      'golang.org/x/crypto/hkdf',
      'golang.org/x/crypto/internal/alias',
      'golang.org/x/crypto/internal/poly1305',
      'golang.org/x/crypto/pbkdf2',
      'golang.org/x/crypto/scrypt',
      'golang.org/x/crypto/ssh',
      'golang.org/x/crypto/ssh/agent',
      'golang.org/x/crypto/ssh/internal/bcrypt_pbkdf'
    ]

  [mod.'golang.org/x/exp']
    version = 'v0.0.0-20260410095643-746e56fc9e2f'
    hash = 'sha256-JaDJGLIRoJjjvsg3dgfFuo7XApEJO2V4kUDmd58qTLI='
    goVersion = '1.25.0'
    vendorPackages = [
      'golang.org/x/exp/constraints'
    ]




  [mod.'golang.org/x/sys']
    version = 'v0.43.0'
    hash = 'sha256-aDQXqSTZES2l/132PBxhZN4ywldpPyfm7LByYCHzzwM='
    goVersion = '1.25.0'
    vendorPackages = [
      'golang.org/x/sys/cpu',
      'golang.org/x/sys/unix'
    ]


  [mod.'golang.org/x/term']
    version = 'v0.42.0'
    hash = 'sha256-FCiDvAfq7dgBGQuiDYDFJbj/JPawhrmPF2qdUEftQ1c='
    goVersion = '1.25.0'
    vendorPackages = [
      'golang.org/x/term'
    ]

  [mod.'golang.org/x/text']
    version = 'v0.36.0'
    hash = 'sha256-/0t9C6Mc8kYjxweFB0us2lGKo8GovHhBiq5nlMOppC0='
    goVersion = '1.25.0'
    vendorPackages = [
      'golang.org/x/text/runes',
      'golang.org/x/text/transform',
      'golang.org/x/text/unicode/norm'
    ]




  [mod.'golang.org/x/xerrors']
    version = 'v0.0.0-20240903120638-7835f813f4da'
    hash = 'sha256-bE7CcrnAvryNvM26ieJGXqbAtuLwHaGcmtVMsVnksqo='
    goVersion = '1.18'
    vendorPackages = [
      'golang.org/x/xerrors',
      'golang.org/x/xerrors/internal'
    ]



